grafana:
  grafana.ini:
    unified_alerting:
      enabled: true
    alerting:
      enabled: false

  extraConfigmapMounts:
    - name: grafana-alerts
      configMap: grafana-alerts
      mountPath: /etc/grafana/provisioning/alerting
      readOnly: true
